# Generated by Django 4.1.1 on 2022-10-07 03:11

import almacen.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarritoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pa', 'Pagado'), ('pe', 'Pendiente')], default='pa', max_length=2)),
                ('fechaEntrega', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, validators=[almacen.validators.validar_longitudnombre])),
                ('descripcion', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('idcategoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categoria', to='almacen.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, validators=[almacen.validators.validar_longitudnombre])),
                ('correo', models.EmailField(max_length=254)),
                ('contrasenia', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, validators=[almacen.validators.validar_longitudnombre])),
                ('telefonos', models.TextField()),
                ('responsable', models.TextField()),
                ('direccion', models.TextField()),
                ('correo', models.EmailField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, validators=[almacen.validators.validar_longitudnombre])),
                ('codigo', models.CharField(max_length=100, null=True)),
                ('archivo', models.ImageField(upload_to='images/')),
                ('unidades', models.CharField(choices=[('u', 'Unidades'), ('kg', 'Kilogramos'), ('l', 'Litros')], default='u', max_length=2)),
                ('descuento', models.FloatField(default=0)),
                ('descripcion', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('idcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria_producto', to='almacen.categoria')),
                ('idfabricante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabricante', to='almacen.fabricante')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCarritoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(validators=[almacen.validators.validar_cantidad])),
                ('precio', models.FloatField(validators=[almacen.validators.validar_precio])),
                ('idCarritoCompra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrito', to='almacen.carritocompra')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='almacen.producto')),
            ],
        ),
        migrations.AddField(
            model_name='carritocompra',
            name='idcliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='almacen.cliente'),
        ),
        migrations.CreateModel(
            name='Almace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, validators=[almacen.validators.validar_longitudnombre])),
                ('cantidad', models.IntegerField(validators=[almacen.validators.validar_cantidad])),
                ('fecharegistro', models.DateField()),
                ('preciounitarioventa', models.DecimalField(decimal_places=2, max_digits=10, validators=[almacen.validators.validar_precio])),
                ('preciounitariocompra', models.DecimalField(decimal_places=2, max_digits=10, validators=[almacen.validators.validar_precio])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('idproducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.producto')),
            ],
        ),
    ]
